### ISSUE TITLE
Deprecated Warnings on PHP 8.x

### ISSUE THREAD

**Issue by ipajen** [toolstack/gp-auto-extract#7]
auto_detect_line_endings is deprecated

`
wp-content/plugins/gp-auto-extract-main/src/wp-includes/pomo/po.php:24
ini_set()
wp-content/plugins/gp-auto-extract-main/src/wp-includes/pomo/po.php:24
GP_Auto_Extract->extract_project()
wp-content/plugins/gp-auto-extract-main/gp-auto-extract.php:562
GP_Auto_Extract->admin_page()
wp-includes/class-wp-hook.php:324
do_action('settings_page_gp-auto-extract')
wp-admin/admin.php:259
`

Creation of dynamic property MakePOT::$extractor is deprecated
`
wp-content/plugins/gp-auto-extract-main/include/extract/makepot.php:158
MakePOT->__construct()
wp-content/plugins/gp-auto-extract-main/gp-auto-extract.php:384
GP_Auto_Extract->extract_project()
wp-content/plugins/gp-auto-extract-main/gp-auto-extract.php:562
GP_Auto_Extract->admin_page()
wp-includes/class-wp-hook.php:324
do_action('settings_page_gp-auto-extract')
wp-admin/admin.php:259
`

**Comment by toolstack** [comment]
Just warnings for now, will get fixed in the next release.

**Comment by toolstack** [comment]
Actually this is already fixed... I just forgot to increment the version number on wordpress.org.

I've fixed that so grab the update and see if this works now.

**Comment by ipajen** [comment]
The issue still exist. i am using the main bransch directly to have the latest code.
The warnings comes when going to `/blog/wp-admin/options-general.php?page=gp-auto-extract.php` and choose to extract.

**Comment by BenBornschein** [comment]
The problem still exists.

**Comment by toolstack** [comment]
So the first one really shouldn't be generating a warning, as it should be suppressed, but I've remove the line as it is probably safe to do so at this point in our use case as we're creating the po files, not reading existing ones.  

The second has been fixed as well.

Both of these come from code in the wp i18n project so I've only fixed them locally.
